title: "Robot Air Hockey"
description: "A manipulation testbed for robot learning, spanning two simulators and a real robot arm"

# No site-level author: attribution is per page, so it lands on posts only.

url: "https://air-hockey-rl.github.io"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - README.md

repo_url: "https://github.com/CalCharles/air-hockey-rl"
